name: Finance Notifier

on:
  schedule:
    - cron: "0,30 * * * *"   # alle 30 Minuten
  workflow_dispatch:          # manueller Start möglich

jobs:
  run-alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Restore alert_state.json
        uses: actions/download-artifact@v4
        with:
          name: alert_state
          path: json
        continue-on-error: true

      - name: Ensure alert_state.json exists
        run: |
          mkdir -p json
          if [ ! -f json/alert_state.json ]; then
            echo '{}' > json/alert_state.json
            echo "Created empty json/alert_state.json"
          fi
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Write config.json
        run: |
          mkdir -p json
          printf "%s" '${{ secrets.CFG }}' > json/config.json
          echo "config.json created:"
          cat json/config.json
          cat json/alert_state.json
          if [ -f json/alert_state.json ]; then
            echo "alert_state.json exists, content:"
            cat json/alert_state.json
          else
            echo "alert_state.json does not exist"
            # Optional: Erstelle die Datei, falls sie benötigt wird
            echo "{}" > json/alert_state.json
            echo "alert_state.json created with default content:"
            cat json/alert_state.json
          fi
          
          # Validieren von config.json
          python -m json.tool json/config.json > /dev/null || echo "config.json is not valid JSON"
          
      - name: Restore .env
        run: |
          echo "NTFY_URL=${{ secrets.NTFY_TOPIC }}" >> .env
          echo "API_KEY=${{ secrets.LOG_LEVEL }}" >> .env
          
      - name: Run Alerts
        run: python main.py
        
      - name: Save alert_state.json
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: alert_state
          path: json/alert_state.json
